In [1]:
# importing the necessary libraries
import pandas as pd

In [2]:
# installing the missing dependencies
!pip install fastparquet

Requirement already satisfied: fastparquet in /usr/local/lib/python3.13/site-packages (2025.12.0)
Requirement already satisfied: pandas>=1.5.0 in /usr/local/lib/python3.13/site-packages (from fastparquet) (2.3.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/site-packages (from fastparquet) (2.4.1)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.13/site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.13/site-packages (from fastparquet) (2026.1.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/site-packages (from fastparquet) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/site-packages (from pandas>=1.5.0->fastparquet) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.

In [3]:
# Defining the url variables
green_taxi_url = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2025-11.parquet"
zones_url = "https://github.com/DataTalksClub/nyc-tlc-data/releases/download/misc/taxi_zone_lookup.csv"

In [4]:
# Reading the trips data file
df_trips = pd.read_parquet(green_taxi_url)
df_trips.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [5]:
# Reading the zone data file
df_zones = pd.read_csv(zones_url)
df_zones.head()

   LocationID        Borough                     Zone service_zone
0           1            EWR           Newark Airport          EWR
1           2         Queens              Jamaica Bay    Boro Zone
2           3          Bronx  Allerton/Pelham Gardens    Boro Zone
3           4      Manhattan            Alphabet City  Yellow Zone
4           5  Staten Island            Arden Heights    Boro Zone

In [6]:
# Converting the necessary field to timestamp
df_trips['lpep_pickup_datetime'] = pd.to_datetime(df_trips['lpep_pickup_datetime'])

### Question 3

In [7]:
# Selecting trip data in the month of Nov 2025
nov_trips = df_trips[(df_trips['lpep_pickup_datetime'] >= '2025-11-01') & (df_trips['lpep_pickup_datetime'] < '2025-12-01')].reset_index(drop = True)
nov_trips.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.0
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.0
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.5,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.0
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.7,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.0
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.4,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.0

In [8]:
# Displaying the min and max pick up timestamps
print('Min Date:', min(nov_trips.lpep_pickup_datetime))
print('Max Date:', max(nov_trips.lpep_pickup_datetime))

Min Date: 2025-11-01 00:00:13
Max Date: 2025-11-30 23:58:28

In [9]:
# Displaying the columns
nov_trips.columns

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee'],
      dtype='object')

In [10]:
print('Trips in Nov 2025 with trip distance less than or equal to 1 mile:', nov_trips[nov_trips['trip_distance'] <= 1].shape[0])

Trips in Nov 2025 with trip distance less than or equal to 1 mile: 8007

### Question 4

In [11]:
# Filtering the data for trips less than 100 miles
trips_100 = df_trips[df_trips['trip_distance'] < 100].reset_index(drop = True)

# Getting the row with the longest trip distance
longest_trip = max(trips_100['trip_distance'])

# Getting the date of the longest trip
pickup_date = trips_100[trips_100['trip_distance'] == longest_trip ]['lpep_pickup_datetime'].dt.date.iloc[0]

# Displaying the output
print('Pickup Day with the longest trip:', pickup_date)

Pickup Day with the longest trip: 2025-11-14

### Question 5

In [12]:
nov_trips

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.20,...,0.5,1.94,0.0,NaN,1.0,11.64,1.0,1.0,0.00,0.00
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.20,...,0.5,0.00,0.0,NaN,1.0,9.70,2.0,1.0,0.00,0.00
2,2,2025-11-01 01:03:14,2025-11-01 01:15:24,N,1.0,83,160,1.0,2.19,13.50,...,0.5,5.00,0.0,NaN,1.0,21.00,1.0,1.0,0.00,0.00
3,2,2025-11-01 00:10:57,2025-11-01 00:24:53,N,1.0,166,127,1.0,5.44,24.70,...,0.5,0.50,0.0,NaN,1.0,27.70,1.0,1.0,0.00,0.00
4,1,2025-11-01 00:03:48,2025-11-01 00:19:38,N,1.0,166,262,1.0,3.20,18.40,...,1.5,1.00,0.0,NaN,1.0,24.65,1.0,1.0,2.75,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46886,2,2025-11-30 19:58:34,2025-11-30 20:14:28,None,NaN,59,51,NaN,8.50,33.22,...,0.5,0.00,0.0,NaN,1.0,34.72,NaN,NaN,NaN,0.00
46887,2,2025-11-30 19:34:00,2025-11-30 19:46:00,None,NaN,74,151,NaN,1.73,13.86,...,0.5,0.77,0.0,NaN,1.0,16.13,NaN,NaN,NaN,0.00
46888,2,2025-11-30 21:46:46,2025-11-30 22:17:55,None,NaN,33,163,NaN,7.52,38.42,...,0.5,1.00,0.0,NaN,1.0,44.42,NaN,NaN,NaN,0.75
46889,2,2025-11-30 21:00:00,2025-11-30 21:15:00,None,NaN,16,95,NaN,5.61,24.67,...,0.5,0.00,0.0,NaN,1.0,26.17,NaN,NaN,NaN,0.00
46890,2,2025-11-30 23:26:00,2025-11-30 23:42:00,None,NaN,65,87,NaN,2.91,14.46,...,0.5,3.89,0.0,NaN,1.0,23.35,NaN,NaN,NaN,0.75

In [13]:
# Merging the trips data with the zone data based on pickup location id
merged_df1 = nov_trips.merge(df_zones, how = 'left', left_on = 'PULocationID', right_on = 'LocationID')

# Filtering the data for data wrt to pickups on Nov 18, 2025
nov18_trips = merged_df1[(merged_df1['lpep_pickup_datetime'] >= "2025-11-18") & (merged_df1['lpep_pickup_datetime'] < "2025-11-19")]
nov18_trips.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee,LocationID,Borough,Zone,service_zone
22411,2,2025-11-18 08:07:00,2025-11-18 08:19:15,N,1.0,74,75,1.0,1.40,12.1,...,1.0,17.00,1.0,1.0,0.00,0.0,74,Manhattan,East Harlem North,Boro Zone
22412,2,2025-11-18 08:19:54,2025-11-18 08:29:08,N,1.0,75,236,1.0,1.33,10.0,...,1.0,17.10,1.0,1.0,2.75,0.0,75,Manhattan,East Harlem South,Boro Zone
22413,2,2025-11-18 08:42:22,2025-11-18 08:53:49,N,1.0,74,236,1.0,1.97,12.1,...,1.0,19.62,1.0,1.0,2.75,0.0,74,Manhattan,East Harlem North,Boro Zone
22520,2,2025-11-18 09:08:07,2025-11-18 09:14:44,N,1.0,74,166,1.0,0.86,7.9,...,1.0,11.00,1.0,1.0,0.00,0.0,74,Manhattan,East Harlem North,Boro Zone
22521,2,2025-11-18 09:37:57,2025-11-18 09:52:39,N,1.0,74,116,1.0,2.16,15.6,...,1.0,22.23,1.0,1.0,0.00,0.0,74,Manhattan,East Harlem North,Boro Zone

In [14]:
# Getting the zone with the highest amount
grouped_df1 = nov18_trips.groupby('Zone', as_index = False).agg({'total_amount' : 'sum'}).sort_values('total_amount', ascending = False, ignore_index = True)
grouped_df1.head()

                       Zone  total_amount
0         East Harlem North       9281.92
1         East Harlem South       6696.13
2              Central Park       2378.79
3  Washington Heights South       2139.05
4       Morningside Heights       2100.59

In [15]:
print('PickUp Zone with the highest amount on Nov 18, 2025:', grouped_df1.Zone[0])

PickUp Zone with the highest amount on Nov 18, 2025: East Harlem North

### Question 6

In [16]:
# Filtering the data for pick up location as East Harlem North
ehn_df = merged_df1[merged_df1['Zone'] == "East Harlem North"].reset_index(drop = True)

# Merging the zones data wrt dropoff location ids
merged_df2 = ehn_df.merge(df_zones, how = 'left', left_on = 'DOLocationID', right_on = 'LocationID')

# Renaming the conflicting columns for better understanding
merged_df2.rename(columns = {'Borough_x' : 'PUBorough', 'Zone_x' : 'PUZone', 'service_zone_x' : 'PU_service_zone', 
                             'Borough_y' : 'DOBorough', 'Zone_y' : 'DOZone', 'service_zone_y' : 'DO_service_zone'}, inplace = True)
merged_df2.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,congestion_surcharge,cbd_congestion_fee,LocationID_x,PUBorough,PUZone,PU_service_zone,LocationID_y,DOBorough,DOZone,DO_service_zone
0,2,2025-11-01 00:34:48,2025-11-01 00:41:39,N,1.0,74,42,1.0,0.74,7.2,...,0.00,0.0,74,Manhattan,East Harlem North,Boro Zone,42,Manhattan,Central Harlem North,Boro Zone
1,2,2025-11-01 00:18:52,2025-11-01 00:24:27,N,1.0,74,42,2.0,0.95,7.2,...,0.00,0.0,74,Manhattan,East Harlem North,Boro Zone,42,Manhattan,Central Harlem North,Boro Zone
2,2,2025-11-01 00:38:13,2025-11-01 00:55:47,N,1.0,74,262,1.0,3.40,19.8,...,2.75,0.0,74,Manhattan,East Harlem North,Boro Zone,262,Manhattan,Yorkville East,Yellow Zone
3,2,2025-11-01 00:20:44,2025-11-01 00:27:05,N,1.0,74,74,1.0,0.78,7.9,...,0.00,0.0,74,Manhattan,East Harlem North,Boro Zone,74,Manhattan,East Harlem North,Boro Zone
4,2,2025-11-01 00:20:37,2025-11-01 00:24:42,N,1.0,74,41,1.0,0.77,6.5,...,0.00,0.0,74,Manhattan,East Harlem North,Boro Zone,41,Manhattan,Central Harlem,Boro Zone

In [17]:
merged_df2.columns

Index(['VendorID', 'lpep_pickup_datetime', 'lpep_dropoff_datetime',
       'store_and_fwd_flag', 'RatecodeID', 'PULocationID', 'DOLocationID',
       'passenger_count', 'trip_distance', 'fare_amount', 'extra', 'mta_tax',
       'tip_amount', 'tolls_amount', 'ehail_fee', 'improvement_surcharge',
       'total_amount', 'payment_type', 'trip_type', 'congestion_surcharge',
       'cbd_congestion_fee', 'LocationID_x', 'PUBorough', 'PUZone',
       'PU_service_zone', 'LocationID_y', 'DOBorough', 'DOZone',
       'DO_service_zone'],
      dtype='object')

In [18]:
# Getting the record with the largest tip amount
largest_tip = max(merged_df2['tip_amount'])

# Getting the dropoff zone with the largest tip amount
do_zone = merged_df2[merged_df2['tip_amount'] == largest_tip].DOZone.iloc[0]
print('DropOff Zone with the largest tip:', do_zone)

DropOff Zone with the largest tip: Yorkville West